version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    labels:
      - "automerge"
    schedule:
      interval: "daily"
      
#    groups:
#      production-dependencies:
#        dependency-type: "production"
#      nx-dependencies:
#        patterns:
#          - "@nx*"
#      eslint-dependencies:
#        patterns:
#          - "*eslint*"
#      development-dependencies:
#        dependency-type: "development"
