version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels: "automerge"
#    schedule:
#      interval: "weekly"
#      day: "tuesday"
#    groups:
#      production-dependencies:
#        dependency-type: "production"
#      nx-dependencies:
#        patterns:
#          - "@nx*"
#      eslint-dependencies:
#        patterns:
#          - "*eslint*"
#      development-dependencies:
#        dependency-type: "development"
